services:
  loadgenerator:
    build:
      context: ".."
      dockerfile: docker/loadgenerator.Dockerfile
    ulimits:
      nproc: 65535
    extra_hosts:
      - "host.docker.internal:host-gateway"
  director:
    build:
      context: ".."
      dockerfile: docker/director.Dockerfile
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - "${LUA_FILE?No yaml path specified}:/opt/load_generator.yml:ro"
      - "${OUTPUT_DIR?No experiment output directory defined}:/opt/loadgenerator:rw"
      - "${PROFILE?No profile defined}:/opt/profile.csv"
    depends_on:
      - loadgenerator
    entrypoint:
      - "java"
      - "-jar"
      - "/opt/httploadgenerator/httploadgenerator.jar"
      - "director"
      - "--ip"
      - "loadgenerator"
      - "--randomize-users"
      - "--lua"
      - "/opt/load_generator.yml"
      - "--load"
      - "/opt/profile.csv"
      - "-o"
      - "loadgenerator/summary_out.csv"
      - "-t"
      - "${VIRTUAL_USERS}"
      - "--timeout"
      - "${TIMEOUT}"
      - "--wp"
      - "${WARMUP_PAUSE}"
      - "--wd"
      - "${WARMUP_DURATION}"
      - "--wr"
      - "${WARMUP_RPS}"
